CREATE TABLE IF NOT EXISTS FA25_SSC_ETL_LOG (
    run_id INT AUTO_INCREMENT PRIMARY KEY,
    run_timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    phase VARCHAR(50),
    records_extracted INT,
    records_transformed INT,
    records_loaded INT,
    error_message LONGTEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

SHOW CREATE TABLE FA25_SSC_ETL_LOG;